export const FETCH_CHANNELS_IN_PROGRESS = "FETCH_CHANNELS_IN_PROGRESS";
export const FETCH_CHANNELS_RESPONDED = "FETCH_CHANNELS_RESPONDED";
export const FETCH_CHANNELS_RESPONDED_ERR = "FETCH_CHANNELS_RESPONDED_ERR";

export const SORT_CHANNELS = "SORT_CHANNELS";

export const MARK_CHANNEL_AS_FAVOURITE = "MARK_CHANNEL_AS_FAVOURITE";
export const SET_FAVOURITE_CHANNELS = "SET_FAVOURITE_CHANNELS";

export const FETCH_CHANNEL_DETAILS_IN_PROGRESS = "FETCH_CHANNEL_DETAILS_IN_PROGRESS";
export const FETCH_CHANNEL_DETAILS_RESPONDED = "FETCH_CHANNEL_DETAILS_RESPONDED";

export const SET_CHANNEL_DETAILS = "SET_CHANNEL_DETAILS";

export const SET_CHANNEL_LINEAR_EVENTS = "SET_CHANNEL_LINEAR_EVENTS";