export const FETCH_CHANNELS_IN_PROGRESS = "FETCH_CHANNELS_IN_PROGRESS";
export const FETCH_CHANNELS_RESPONDED = "FETCH_CHANNELS_RESPONDED";
export const FETCH_CHANNELS_RESPONDED_ERR = "FETCH_CHANNELS_RESPONDED_ERR";

export const SORT_CHANNELS = "SORT_CHANNELS";

export const MARK_CHANNEL_AS_FAVOURITE = "MARK_CHANNEL_AS_FAVOURITE";
export const SET_FAVOURITE_CHANNELS = "SET_FAVOURITE_CHANNELS";